
######. Northwind SQL Project ############

#. LEVEL 1 – Basic Business KPIs

#. 1. Calculate total revenue of the company.

SELECT 
SUM(unitPrice*quantity*(1-discount)) AS REVENUE
FROM ORDERDETAIL;

#. 2. Show monthly revenue trend (year + month).

SELECT year(ORDERDATE)AS YR,monthname(ORDERDATE)AS MN,
SUM(unitPrice*quantity*(1-discount)) AS REVENUE
FROM ORDERDETAIL
JOIN SALESORDER USING(ORDERID)
GROUP BY YR,MN;

#. 3. Find the average order value.

SELECT AVG(TTLORDR)AS ORDRVAL
FROM
(SELECT ORDERID,
SUM(UnitPrice * Quantity * (1 - Discount))AS TTLORDR
FROM ORDERDETAIL
GROUP BY ORDERID)AS K;

#. 4. Total number of orders per customer.

SELECT CUSTID,
COUNT(DISTINCT orderId) AS CNT
FROM CUSTOMER
JOIN SALESORDER USING(CUSTID)
GROUP BY CUSTID
ORDER BY CNT DESC;

#. 5. Top 10 customers by total spending.

SELECT CUSTID,
SUM(UnitPrice * Quantity * (1 - Discount))AS SPENDING
FROM CUSTOMER
JOIN SALESORDER USING(CUSTID)
JOIN ORDERDETAIL USING(ORDERID)
GROUP BY CUSTID
ORDER BY SPENDING DESC
LIMIT 10;

#. 6. Total revenue by country.

SELECT COUNTRY,
SUM(UnitPrice * Quantity * (1 - Discount)) AS REVENUE
FROM CUSTOMER
JOIN SALESORDER USING(CUSTID)
JOIN ORDERDETAIL USING(ORDERID)
GROUP BY COUNTRY
ORDER BY REVENUE DESC;

#. LEVEL 2 – Product & Category Analysis

#. 7. Top 5 best-selling products (by quantity).

SELECT PRODUCTNAME,
SUM(quantity) AS QUANTITY
FROM PRODUCT 
JOIN ORDERDETAIL USING(PRODUCTID)
GROUP BY PRODUCTNAME
ORDER BY QUANTITY DESC
LIMIT 5;

#. 8. Top 5 products by revenue.

SELECT PRODUCTNAME,
SUM(OD.UNITPRICE*OD.QUANTITY *(1-OD.DISCOUNT))AS REVENUE
FROM PRODUCT  
JOIN ORDERDETAIL OD USING(PRODUCTID)
GROUP BY PRODUCTNAME
ORDER BY REVENUE DESC
LIMIT 5;

#. 9. Revenue by category.

SELECT CATEGORYNAME,
SUM(OD.UNITPRICE*OD.QUANTITY *(1-OD.DISCOUNT)) AS REVENUE
FROM CATEGORY 
JOIN PRODUCT USING(CATEGORYID)
JOIN ORDERDETAIL OD USING(PRODUCTID)
GROUP BY CATEGORYNAME
ORDER BY REVENUE DESC;


#. 10. Which category generates the highest profit?

SELECT CATEGORYNAME,
SUM(OD.UNITPRICE*QUANTITY*(1-DISCOUNT)) AS PROFIT
FROM CATEGORY
JOIN PRODUCT USING(CATEGORYID)
JOIN ORDERDETAIL OD USING(PRODUCTID)
GROUP BY CATEGORYNAME
ORDER BY PROFIT DESC
LIMIT 1;

#. 11. Products that were never ordered.

SELECT PRODUCTNAME
FROM PRODUCT 
LEFT JOIN ORDERDETAIL USING(PRODUCTID)
WHERE ORDERID IS NULL;


#. LEVEL 3 – Customer Insights
#. 12. Customers who placed more than 5 orders.

SELECT CONTACTNAME,
COUNT(DISTINCT ORDERID) AS CNT
FROM CUSTOMER 
JOIN SALESORDER USING(CUSTID)
GROUP BY CONTACTNAME
HAVING CNT>5
ORDER BY CNT DESC;


#. 13. Customers who haven’t ordered in the last 1 year.

SELECT CONTACTNAME,
MAX(ORDERDATE) AS LAST_ORDER
FROM CUSTOMER
LEFT JOIN SALESORDER USING(CUSTID)
GROUP BY CONTACTNAME
HAVING LAST_ORDER IS NULL 
   OR MAX(ORDERDATE) < DATE_SUB(CURDATE(), INTERVAL 1 YEAR);


#. 14. Rank customers by total spending (use window function).

WITH CTE AS(
SELECT CONTACTNAME,
SUM(OD.UNITPRICE*OD.QUANTITY*(1-DISCOUNT))AS SPENDING
FROM CUSTOMER
JOIN SALESORDER USING(CUSTID)
JOIN ORDERDETAIL OD USING(ORDERID)
GROUP BY CONTACTNAME
ORDER by  SPENDING DESC)
SELECT *,row_number() OVER() AS RANKS
FROM CTE;

#. 15. Find customers whose total spending is above average.


SELECT CUSTID, SPENDING
FROM (
    SELECT CUSTID,
           SUM(OD.UNITPRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS SPENDING
    FROM CUSTOMER 
    JOIN SALESORDER USING (CUSTID)
    JOIN ORDERDETAIL OD USING (ORDERID)
    GROUP BY CUSTID
) AS K
HAVING SPENDING > (
    SELECT AVG(SPENDING)
    FROM (
        SELECT SUM(OD.UNITPRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS SPENDING
        FROM CUSTOMER
        JOIN SALESORDER USING (CUSTID)
        JOIN ORDERDETAIL OD USING (ORDERID)
        GROUP BY CUSTID
    ) AS T
);


#. LEVEL 4 – Shipping & Operations
#. 16. Average shipping time (ShippedDate – OrderDate).

SELECT 
AVG(datediff(SHIPPEDDATE,ORDERDATE))AS SHIPPING_TIME
FROM SALESORDER
WHERE SHIPPEDDATE IS NOT NULL;

#. 17. Which shipper handles the most orders?

SELECT SHIPNAME,
COUNT(ORDERID) AS ORDERS
FROM SALESORDER 
JOIN SHIPPER USING(SHIPPERID)
GROUP BY SHIPNAME
ORDER BY ORDERS DESC
LIMIT 1;

#. 18. Orders that were shipped late (ShippedDate > RequiredDate)

SELECT ORDERID, SHIPPEDDATE, REQUIREDDATE
FROM SALESORDER
WHERE SHIPPEDDATE > REQUIREDDATE;

#. 19. Which employee processed the most orders?

SELECT  CONCAT(LASTNAME,' ',FIRSTNAME) AS FULLNAME,
COUNT(ORDERID)AS ORDERS
FROM EMPLOYEE 
JOIN SALESORDER USING(EMPLOYEEID)
GROUP BY FULLNAME
ORDER BY ORDERS DESC
LIMIT 1;

#. 20. Revenue handled by each employee.

SELECT EMPLOYEEID,
SUM(UNITPRICE*QUANTITY*(1-DISCOUNT))AS REVENUE
FROM EMPLOYEE 
JOIN SALESORDER USING(EMPLOYEEID)
JOIN ORDERDETAIL USING(ORDERID)
GROUP BY EMPLOYEEID
ORDER BY REVENUE DESC;


#. LEVEL 5 – Advanced SQL (Interview Level)
#. 21. Running total of monthly revenue (Window function).

WITH CTE AS
(SELECT monthname(ORDERDATE)AS MN,
SUM(UNITPRICE*QUANTITY*(1-DISCOUNT))AS REVENUE
FROM SALESORDER 
JOIN ORDERDETAIL USING(ORDERID)
GROUP BY MN)
SELECT *,SUM(REVENUE) OVER (ORDER BY MN)AS RUNNING_TOTAL
FROM CTE;


#. 22. Year-over-Year revenue growth.


WITH CTE AS
(SELECT YEAR(ORDERDATE) AS YR,
           SUM(UNITPRICE * QUANTITY * (1 - DISCOUNT)) AS REVENUE
    FROM SALESORDER 
    JOIN ORDERDETAIL USING(ORDERID)
    GROUP BY YR
)
SELECT YR,
       REVENUE,
       REVENUE - LAG(REVENUE) OVER (ORDER BY YR) AS YOY_GROWTH
FROM CTE
ORDER BY YR;


#. 23. Rank products within each category by revenue.

WITH CTE AS(
SELECT PRODUCTNAME,CATEGORYNAME,
SUM(OD.UNITPRICE*OD.QUANTITY*(1-OD.DISCOUNT))AS REVENUE
FROM CATEGORY
JOIN PRODUCT USING(CATEGORYID)
JOIN ORDERDETAIL OD USING(PRODUCTID)
GROUP BY PRODUCTNAME,CATEGORYNAME)
SELECT *,RANK() OVER(PARTITION BY CATEGORYNAME ORDER BY REVENUE DESC)AS RANKK
FROM CTE;

#. 24. Find the second highest selling product in each category.

WITH NEWCTE AS
(
WITH CTE AS
(
SELECT PRODUCTNAME,CATEGORYNAME,
SUM(QUANTITY)AS SELLING
FROM CATEGORY 
JOIN PRODUCT USING(CATEGORYID)
JOIN ORDERDETAIL USING(PRODUCTID)
GROUP BY PRODUCTNAME,CATEGORYNAME)
SELECT*,row_number() OVER(partition by CATEGORYNAME ORDER BY SELLING DESC) AS RN
FROM CTE)
SELECT * FROM NEWCTE
WHERE RN=2;

#. 25. Identify top 20% customers contributing most revenue

WITH NEWCTE AS
(
WITH CTE AS 
(
SELECT CONTACTNAME,
SUM(UNITPRICE*QUANTITY*(1-DISCOUNT))AS REVENUE
FROM CUSTOMER 
JOIN SALESORDER USING(CUSTID)
JOIN ORDERDETAIL USING(ORDERID)
GROUP BY CONTACTNAME)
SELECT*,ntile(5)OVER(ORDER BY REVENUE DESC)AS MOST_REVENUE
FROM CTE)
SELECT * FROM NEWCTE
WHERE MOST_REVENUE=1;



#. LEVEL 6 – Business Thinking Questions
#. 26. Which country has high sales but low average order value?


WITH CTE AS
(
    SELECT COUNTRY,
           ORDERID,
           SUM(UnitPrice * Quantity * (1 - Discount)) AS ORDERVALUE
    FROM CUSTOMER 
    JOIN SALESORDER USING (CUSTID)
    JOIN ORDERDETAIL USING (ORDERID)
    GROUP BY COUNTRY, ORDERID
)

SELECT COUNTRY,
       SUM(ORDERVALUE) AS CNT,
       AVG(ORDERVALUE) AS ORDERVALUE
FROM CTE
GROUP BY COUNTRY
ORDER BY CNT DESC, ORDERVALUE ASC;



#. 27. Which employees generate high revenue but have higher late shipments?

WITH CTE AS
(
    SELECT 
        E.EMPLOYEEID,
        CONCAT(E.FIRSTNAME, ' ', E.LASTNAME) AS EMPLOYEENAME,
        SO.ORDERID,
        
        SUM(OD.UNITPRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS ORDERVALUE,
        
        CASE 
            WHEN SO.SHIPPEDDATE > SO.REQUIREDDATE THEN 1
            ELSE 0
        END AS LATE_FLAG
        
    FROM EMPLOYEE E
    JOIN SALESORDER SO USING (EMPLOYEEID)
    JOIN ORDERDETAIL OD USING (ORDERID)
    
    GROUP BY E.EMPLOYEEID, EMPLOYEENAME, SO.ORDERID, LATE_FLAG
)

SELECT 
    EMPLOYEEID,
    EMPLOYEENAME,
    SUM(ORDERVALUE) AS TOTAL_REVENUE,
    SUM(LATE_FLAG) AS TOTAL_LATE_SHIPMENTS,
    COUNT(ORDERID) AS TOTAL_ORDERS
FROM CTE
GROUP BY EMPLOYEEID, EMPLOYEENAME
ORDER BY TOTAL_REVENUE DESC, TOTAL_LATE_SHIPMENTS DESC;


#. 28. Seasonal trend analysis – which month performs best?

WITH CTE AS
(
    SELECT 
        MONTH(ORDERDATE) AS MONTH_NO,
        ORDERID,
        SUM(UNITPRICE * QUANTITY * (1 - DISCOUNT)) AS ORDERVALUE
        
    FROM SALESORDER
    JOIN ORDERDETAIL USING (ORDERID)
    
    GROUP BY MONTH_NO, ORDERID
)

SELECT 
    MONTH_NO,
    SUM(ORDERVALUE) AS TOTAL_REVENUE,
    COUNT(ORDERID) AS TOTAL_ORDERS,
    AVG(ORDERVALUE) AS AVG_ORDER_VALUE
FROM CTE
GROUP BY MONTH_NO
ORDER BY TOTAL_REVENUE DESC;


#. 29. Find revenue contribution percentage by each category

WITH CTE AS
(
    SELECT 
        C.CATEGORYNAME,
        OD.ORDERID,
        SUM(OD.UNITPRICE * OD.QUANTITY * (1 - OD.DISCOUNT)) AS ORDERVALUE
        
    FROM CATEGORY C
    JOIN PRODUCT USING (CATEGORYID)
    JOIN ORDERDETAIL OD USING (PRODUCTID)
    
    GROUP BY C.CATEGORYNAME, OD.ORDERID
)

SELECT 
    CATEGORYNAME,
    SUM(ORDERVALUE) AS TOTAL_REVENUE,
    
    ROUND(
        SUM(ORDERVALUE) * 100 /
        SUM(SUM(ORDERVALUE)) OVER (), 
        2
    ) AS REVENUE_PERCENTAGE
    
FROM CTE
GROUP BY CATEGORYNAME
ORDER BY REVENUE_PERCENTAGE DESC;































